// <auto-generated />
using System;
using Harfiyat_DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Harfiyat_DataAccess.Migrations
{
    [DbContext(typeof(ConsturactionContext))]
    [Migration("20250215113907_add_data")]
    partial class add_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("Harfiyat_Entities.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobRequestId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Harfiyat_Entities.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localiton")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobRequestId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Harfiyat_Entities.Entities.JobRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsApproved = false,
                            JobTitle = "Bina Yıkımı",
                            RequestDate = new DateTime(2025, 2, 15, 14, 39, 7, 744, DateTimeKind.Local).AddTicks(3878),
                            RequestedBy = "Ferhat Ersoy"
                        },
                        new
                        {
                            Id = 2,
                            IsApproved = false,
                            JobTitle = "Kanalizasyon kazimi",
                            RequestDate = new DateTime(2025, 2, 15, 14, 39, 7, 744, DateTimeKind.Local).AddTicks(3892),
                            RequestedBy = "Osman Ersoy"
                        },
                        new
                        {
                            Id = 3,
                            IsApproved = true,
                            JobTitle = "Duvar Yikimi",
                            RequestDate = new DateTime(2025, 2, 15, 14, 39, 7, 744, DateTimeKind.Local).AddTicks(3893),
                            RequestedBy = "İlker Yalçın"
                        },
                        new
                        {
                            Id = 4,
                            IsApproved = false,
                            JobTitle = "Çiçek çukuru kazma",
                            RequestDate = new DateTime(2025, 2, 15, 14, 39, 7, 744, DateTimeKind.Local).AddTicks(3894),
                            RequestedBy = "Uzay Can"
                        });
                });

            modelBuilder.Entity("Harfiyat_Entities.Entities.Image", b =>
                {
                    b.HasOne("Harfiyat_Entities.Entities.JobRequest", "JobRequest")
                        .WithMany("Images")
                        .HasForeignKey("JobRequestId");

                    b.Navigation("JobRequest");
                });

            modelBuilder.Entity("Harfiyat_Entities.Entities.Job", b =>
                {
                    b.HasOne("Harfiyat_Entities.Entities.JobRequest", "JobRequest")
                        .WithMany("Jobs")
                        .HasForeignKey("JobRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRequest");
                });

            modelBuilder.Entity("Harfiyat_Entities.Entities.JobRequest", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
